language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp .travis/settings.xml $HOME/.m2/settings.xml
  # Force caching of maven plugins used during deploy phase
  - mvn deploy:help versions:help help:help

script:
  - mvn install -Dtest=\!SecureClientTest

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - chmod u+x .travis/trigger_deps.sh
  - if [ -n "$TRAVIS_TAG" ]; then .travis/trigger_deps.sh; fi

notifications:
  slack:
    secure: 7On5L//ucWX/SzvcypOHINJOkUNWX4rcjqj4afxCfxaHqPEs7SSn596LWoPQ4hy+zS8EhzCgw3BQo1brKssFd8JXsecdgZ9r0NTGzBOV1CF9eQVEL8rz3a5Jh6Jjiso18JbMQMvENIUpU2UfZ02hstMNEW7C/bMPEp3jdL6W5dyBmdBy46DJYu/DHJZ1Xk403SFs0QRd4CqOxPpzqYlDypvU54JHdB1oKLnzxMoJHejlsa0ek44qSJLp4Q/EftvSoUsNJMwBG4S/aDd9vPNQrUu7JW7TGc849yW0IIP0/C1djo1qMOFhdw5Bx2Y2BZ+9j7LfaR+CKRWO6ktJfKFgTR5C6DpgH3+rWfW6McWWdjDRVEpFAfhX1RVL27zUMsbaEy0mPJVh2rxFnSG+wsEJLNBW5fU1IC1zxz9irPkCIiyrNSy6mMuaDpqJHQIht2ttyWhYeo0t+z+KuS/hXCgKrUKprcAkEMu+PDJcT51o8sTdkZ4haB24NFNg/gaFMfouQgeqiTV68fLgj4Yj4qrMrCQvJNn6xO9q99reviN9Mc4NlnYsylq2W52gZv/rO36DRMU5vgVaDHVCEBYcQDEIz//hrpPoMpm2nyVkwYpIDaxFIN3lsm4DauQNGspgb9U6D1V2VGt/9JiU92L/u7IR3/filn0MIisb7Y+NGldU27M=
