language: java
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-wire.git
- cd vlingo-wire && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: d-led
  on:
    branch: master
  key:
    secure: 6yKgHvJ0M6KheTnmfMHwJFz9Z+WKk624JfxsJjbbjUpc+Tlp9LqFjMPPDdRJjhlxRpApSr5YFjqGJCiHVNAMxAMyzsa7Iu3hXk8OzS449kwDY7EY9nbpMsFiKGJuxlP8GTy6EcBljdxL9WBVeJRyeutsbFI92jXW5g2ta3wvXbspdbpNnSZukuGMs4WEUAlMzIdkApjM5GxWyExGSM4eMDgbzs9BICOF6vH5a/PD0KM+Y6yuOiTyInaetbosxuh0Nr+qvWIbO/SdCTEd5lOaTMUK3jDDhfwCZpi/C4r8brRcNeRh5kg5Z0BBZMW0hUWyxuX3QEcSLyEaSI/XhhhImCHpEUY7PnfmR2w54ZS/UbkddCeyb1sYCc/7QwQPM4JgZxNMQZFIvgG3bLRKPoC1tqICK+KvEj7IEc+46TUxOOpFE/4qS3SScMuDq38M2cfDVelLceVIH1hhjCEIOP+WP7iLOf1OFzZNTLsrnnZDFIh+23VNh0B1gPL1KPPkmjOzfrPPhcQvlm7Q+PNCuopvNFYa7GbdlS7iK1kXZxcvwOmN7nmHevz3yShaYJ+r1AbaGKEUf9/7cyRp51xdQtRMhwL9VQJ3Jyr5p2C7xgBIFENHAV5m8kvxZ8nX2vXdtATTcSMf85/NJBpqRf1xOVyPvU2iBsInXQk/w7Stxsmp9qM=
  passphrase:
    secure: imRJ7qgiZ1cs69QUwLp5mlRvsFgxW5aUcAC1YZBpXU7W73ZDpBiL0KAOZwXyhEtBwR/mgNUb7qtrQkEyhLWdBM7SFf0IxACLC2FoIy002SAyD5eCzwzaQBvpi4m2v3PHTdxGeBi3pQQXo0b71RjXKpC9mNHfj7UrO+lLRV86UsyRwjIfhm/p/bthvfvKDMXShdPIwBILAcBAVRmPK2fb6G4D8h9C8KecgnM2pzLTntuXHNboOL/uG9+F2tVx6ykwY329f4NUQ+LhBljoEixC0WIpjDZHrMaeCyahRb58ygpn5Pi3SpUnZRgrdJzl/D3Er39iEjrKoqckII2cdmThku/chd3ES9n3yE6p0Y/rS9uiW4Y6Cra0WKfwzvkiITPuLbRbIsCOGLnCTbVve5NGYvc+nueuZLmo9pamDQi7q7T60YUk9FtBju7xvysNKksGpEekMtgMbyCpn+yPvsiX73Bq6XGduMifuEj/aIRsqHBzkHyi33GYH/8A6K/gxZP/KnklzPsLvjzLMMFSsNmNq8XiVVCYw3oVZBaZecsa4fC4gamFRb1tJToCHnMU2O+3Bmhhz06eSPQcwh9MpHtAychpgDmAV3cR8nuXO/a1pgrbhFQwmAJpN2ODhTft8gGOO/a43ul3Czmsrib4OqJw4YTYLyxi39Elxdo2LKpOmp0=
notifications:
  slack:
    secure: 7On5L//ucWX/SzvcypOHINJOkUNWX4rcjqj4afxCfxaHqPEs7SSn596LWoPQ4hy+zS8EhzCgw3BQo1brKssFd8JXsecdgZ9r0NTGzBOV1CF9eQVEL8rz3a5Jh6Jjiso18JbMQMvENIUpU2UfZ02hstMNEW7C/bMPEp3jdL6W5dyBmdBy46DJYu/DHJZ1Xk403SFs0QRd4CqOxPpzqYlDypvU54JHdB1oKLnzxMoJHejlsa0ek44qSJLp4Q/EftvSoUsNJMwBG4S/aDd9vPNQrUu7JW7TGc849yW0IIP0/C1djo1qMOFhdw5Bx2Y2BZ+9j7LfaR+CKRWO6ktJfKFgTR5C6DpgH3+rWfW6McWWdjDRVEpFAfhX1RVL27zUMsbaEy0mPJVh2rxFnSG+wsEJLNBW5fU1IC1zxz9irPkCIiyrNSy6mMuaDpqJHQIht2ttyWhYeo0t+z+KuS/hXCgKrUKprcAkEMu+PDJcT51o8sTdkZ4haB24NFNg/gaFMfouQgeqiTV68fLgj4Yj4qrMrCQvJNn6xO9q99reviN9Mc4NlnYsylq2W52gZv/rO36DRMU5vgVaDHVCEBYcQDEIz//hrpPoMpm2nyVkwYpIDaxFIN3lsm4DauQNGspgb9U6D1V2VGt/9JiU92L/u7IR3/filn0MIisb7Y+NGldU27M=
